# Generated by Django 2.1.4 on 2018-12-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181227_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_quotes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Quote'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_first_read',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_last_read',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_purchased',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
