# Generated by Django 2.1.4 on 2018-12-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181227_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_first_read',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_last_read',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_purchased',
            field=models.DateField(null=True),
        ),
    ]
