# Generated by Django 2.1.4 on 2018-12-27 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20181227_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_quotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Quote'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
