# Generated by Django 2.1.4 on 2018-12-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181227_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='note',
        ),
    ]
